In [120]:
import pandas as pd
import seaborn as sns

In [121]:
df = pd.read_csv("../Data/cleaned_data.csv")
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

# Label encoding for binary columns

In [122]:
df.columns

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [123]:
df[df['tenure'] == 0]

Empty DataFrame
Columns: [gender, SeniorCitizen, Partner, Dependents, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges, Churn]
Index: []

In [124]:
df['Average'] = df['TotalCharges'] / df['tenure']

In [125]:
binary_col = [
    'gender', 
    'Partner', 
    'Dependents', 
    'PhoneService', 
    'MultipleLines',
    'OnlineSecurity', 
    'OnlineBackup', 
    'DeviceProtection',
    'TechSupport',
    'StreamingTV', 
    'StreamingMovies',
    'PaperlessBilling',
    'Churn'
]

for col in binary_col:
    df[col] = df[col].map({'Male':1, 'Female':0}) if col == 'gender' else df[col].map({'Yes':1, 'No':0})

#  Ordianl encoding for "Contract column"

In [126]:
con_map = {
    'Month-to-month':0,
    'One year':1,
    'Two year':2
}
df['Contract'] = df['Contract'].map(con_map)

# One_hot encoding for multi-cetagory columns

In [127]:
InternetService_dummy = pd.get_dummies(
    df['InternetService'], 
    prefix='InternetService', 
    drop_first=True
).astype('int')

In [128]:
PaymentMethod_dummy = pd.get_dummies(
    df['PaymentMethod'], 
    prefix='PaymentMethod', 
    drop_first=True,
    dummy_na=False
).astype('int')

In [129]:
df = pd.concat([df, InternetService_dummy, PaymentMethod_dummy], axis=1)

In [130]:
df = df.drop(['InternetService', 'PaymentMethod'], axis=1)

In [131]:
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,OnlineSecurity,OnlineBackup,DeviceProtection,...,PaperlessBilling,MonthlyCharges,TotalCharges,Churn,Average,InternetService_Fiber optic,InternetService_No,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,0,1,0,1,0,0,0,1,0,...,1,29.85,29.85,0,29.850000,0,0,0,1,0
1,1,0,0,0,34,1,0,1,0,1,...,0,56.95,1889.50,0,55.573529,0,0,0,0,1
2,1,0,0,0,2,1,0,1,1,0,...,1,53.85,108.15,1,54.075000,0,0,0,0,1
3,1,0,0,0,45,0,0,1,0,1,...,0,42.30,1840.75,0,40.905556,0,0,0,0,0
4,0,0,0,0,2,1,0,0,0,0,...,1,70.70,151.65,1,75.825000,1,0,0,1,0

In [132]:
df.to_csv("../Data/preprocessed.csv", index=False)