In [220]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, PowerTransformer
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import (
    accuracy_score, 
    recall_score, 
    f1_score, 
    confusion_matrix, 
    classification_report
)
from imblearn.over_sampling import SMOTE
import warnings
warnings.filterwarnings('ignore')

In [221]:
df = pd.read_csv("../Data/preprocessed.csv")
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,OnlineSecurity,OnlineBackup,DeviceProtection,...,PaperlessBilling,MonthlyCharges,TotalCharges,Churn,Average,InternetService_Fiber optic,InternetService_No,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,0,1,0,1,0,0,0,1,0,...,1,29.85,29.85,0,29.850000,0,0,0,1,0
1,1,0,0,0,34,1,0,1,0,1,...,0,56.95,1889.50,0,55.573529,0,0,0,0,1
2,1,0,0,0,2,1,0,1,1,0,...,1,53.85,108.15,1,54.075000,0,0,0,0,1
3,1,0,0,0,45,0,0,1,0,1,...,0,42.30,1840.75,0,40.905556,0,0,0,0,0
4,0,0,0,0,2,1,0,0,0,0,...,1,70.70,151.65,1,75.825000,1,0,0,1,0

In [222]:
x = df.drop(['Churn'], axis=1)
y = df[['Churn']]

In [223]:
xtrain, xtest, ytrain, ytest = train_test_split(
    x, y, 
    random_state=42,
    test_size=0.2,                                                                         
    stratify=y
)

In [224]:
xtrain_no_scale = xtrain.copy()
ytrain_no_scale = ytrain.copy()

In [225]:
smote = SMOTE(random_state=42)
xtrain_no_scale_res, ytrain_no_scale_res = smote.fit_resample(xtrain_no_scale, ytrain_no_scale)

# Applying without Scalling

In [226]:
algorithms = {
    "LogisticRegression": LogisticRegression(),
    "KNeighborsClassifier": KNeighborsClassifier(),
    "RandomForestClassifier": RandomForestClassifier(),
    "XGBClassifier": XGBClassifier(),
    "GaussianNB": GaussianNB()
}

In [227]:
for model_name, models in algorithms.items():
    print(model_name)
    model = models.fit(xtrain_no_scale_res, ytrain_no_scale_res)
    print(f"Train Score: {model.score(xtrain_no_scale_res, ytrain_no_scale_res)}")
    print(f"Test Score: {model.score(xtest, ytest)}")
    pred = model.predict(xtest)
    print(f"confusion_matrix:\n{confusion_matrix(ytest, pred)}")
    print(f"accuracy_score: {accuracy_score(ytest, pred)}")
    print(f"recall_score: {recall_score(ytest, pred)}")
    print(f"f1_score: {f1_score(ytest, pred)}")
    print("____________________")

LogisticRegression
Train Score: 0.8198547215496368
Test Score: 0.7512437810945274
confusion_matrix:
[[799 234]
 [116 258]]
accuracy_score: 0.7512437810945274
recall_score: 0.6898395721925134
f1_score: 0.5958429561200924
____________________
KNeighborsClassifier
Train Score: 0.8440677966101695
Test Score: 0.6915422885572139
confusion_matrix:
[[717 316]
 [118 256]]
accuracy_score: 0.6915422885572139
recall_score: 0.6844919786096256
f1_score: 0.5412262156448203
____________________
RandomForestClassifier
Train Score: 0.9990314769975787
Test Score: 0.7796730632551528
confusion_matrix:
[[859 174]
 [136 238]]
accuracy_score: 0.7796730632551528
recall_score: 0.6363636363636364
f1_score: 0.6055979643765903
____________________
XGBClassifier
Train Score: 0.9630750605326877
Test Score: 0.7654584221748401
confusion_matrix:
[[855 178]
 [152 222]]
accuracy_score: 0.7654584221748401
recall_score: 0.5935828877005348
f1_score: 0.5736434108527132
____________________
GaussianNB
Train Score: 0.8056900726392252
Test Score: 0.7491115849324804
confusion_matrix:
[[799 234]
 [119 255]]
accuracy_score: 0.7491115849324804
recall_score: 0.6818181818181818
f1_score: 0.5909617612977984
____________________

# Apply with Scaling

In [228]:
scale_xtrain = xtrain.copy()
scale_xtest = xtest.copy()

In [229]:
sts = StandardScaler()
continuous_cols = ['tenure', 'MonthlyCharges', 'TotalCharges', 'Average']
scale_xtrain[continuous_cols] = sts.fit_transform(scale_xtrain[continuous_cols])
scale_xtest[continuous_cols] = sts.transform(scale_xtest[continuous_cols])

In [230]:
smote = SMOTE(random_state=42)
scale_xtrain_res, scale_ytrain_res = smote.fit_resample(scale_xtrain, ytrain)

In [231]:
for model_name, models in algorithms.items():
    print(model_name)
    model1 = models.fit(scale_xtrain_res, scale_ytrain_res)
    print(f"Train Score: {model1.score(scale_xtrain_res, scale_ytrain_res)}")
    print(f"Test Score: {model1.score(scale_xtest, ytest)}")
    pred1 = model1.predict(scale_xtest)
    print(f"confusion_matrix:\n{confusion_matrix(ytest, pred1)}")
    print(f"accuracy_score: {accuracy_score(ytest, pred1)}")
    print(f"recall_score: {recall_score(ytest, pred1)}")
    print(f"f1_score: {f1_score(ytest, pred1)}")
    print("____________________")

LogisticRegression
Train Score: 0.8033898305084746
Test Score: 0.7455579246624022
confusion_matrix:
[[774 259]
 [ 99 275]]
accuracy_score: 0.7455579246624022
recall_score: 0.7352941176470589
f1_score: 0.6057268722466961
____________________
KNeighborsClassifier
Train Score: 0.8665859564164649
Test Score: 0.7085998578535891
confusion_matrix:
[[721 312]
 [ 98 276]]
accuracy_score: 0.7085998578535891
recall_score: 0.7379679144385026
f1_score: 0.5738045738045738
____________________
RandomForestClassifier
Train Score: 0.9990314769975787
Test Score: 0.7782515991471215
confusion_matrix:
[[843 190]
 [122 252]]
accuracy_score: 0.7782515991471215
recall_score: 0.6737967914438503
f1_score: 0.6176470588235294
____________________
XGBClassifier
Train Score: 0.9544794188861986
Test Score: 0.7604832977967306
confusion_matrix:
[[831 202]
 [135 239]]
accuracy_score: 0.7604832977967306
recall_score: 0.6390374331550802
f1_score: 0.5865030674846625
____________________
GaussianNB
Train Score: 0.7843825665859564
Test Score: 0.7327647476901208
confusion_matrix:
[[751 282]
 [ 94 280]]
accuracy_score: 0.7327647476901208
recall_score: 0.7486631016042781
f1_score: 0.5982905982905983
____________________

In [232]:
skewness = xtrain.skew()
print(skewness)

gender                                  -0.007469
SeniorCitizen                            1.837422
Partner                                  0.055859
Dependents                               0.875416
tenure                                   0.237016
PhoneService                            -2.726233
MultipleLines                            0.307656
OnlineSecurity                           0.942336
OnlineBackup                             0.627296
DeviceProtection                         0.649508
TechSupport                              0.900568
StreamingTV                              0.455580
StreamingMovies                          0.450213
Contract                                 0.625201
PaperlessBilling                        -0.388751
MonthlyCharges                          -0.230273
TotalCharges                             0.954139
Average                                 -0.219559
InternetService_Fiber optic              0.235999
InternetService_No                       1.389595
PaymentMethod_Credit card (automatic)    1.380636
PaymentMethod_Electronic check           0.680306
PaymentMethod_Mailed check               1.314560
dtype: float64

In [233]:
skewed_freature = skewness[abs(skewness) > .5]
print(f"Skewed_freature:\n{skewed_freature}")

Skewed_freature:
SeniorCitizen                            1.837422
Dependents                               0.875416
PhoneService                            -2.726233
OnlineSecurity                           0.942336
OnlineBackup                             0.627296
DeviceProtection                         0.649508
TechSupport                              0.900568
Contract                                 0.625201
TotalCharges                             0.954139
InternetService_No                       1.389595
PaymentMethod_Credit card (automatic)    1.380636
PaymentMethod_Electronic check           0.680306
PaymentMethod_Mailed check               1.314560
dtype: float64

In [234]:
gnb = GaussianNB()
gnb_param_grid = {
    'var_smoothing': [1e-12, 1e-10, 1e-9, 1e-8, 1e-7, 1e-6, 1e-5]
}

gnb_grid = GridSearchCV(
    estimator=gnb, param_grid=gnb_param_grid, cv = 10, scoring='f1'
)
gnb_model = gnb_grid.fit(scale_xtrain_res, scale_ytrain_res)
print(f"Train score: {gnb_model.score(scale_xtrain_res, scale_ytrain_res)}")
print(f"Test score: {gnb_model.score(scale_xtest, ytest)}")
gnb_pred = gnb_model.predict(scale_xtest)
print(f"Accuracy Score: {accuracy_score(ytest, gnb_pred)}")
print(f"Recall Score: {recall_score(ytest, gnb_pred)}")
print(f"f1 Score: {f1_score(ytest, gnb_pred)}")
print(f"confussion matrix:\n{confusion_matrix(ytest, gnb_pred)}")
print(f"Best Parameter: {gnb_model.best_params_}")
print(f'Best Score: {gnb_model.best_score_}')

Train score: 0.7906922082500881
Test score: 0.5982905982905983
Accuracy Score: 0.7327647476901208
Recall Score: 0.7486631016042781
f1 Score: 0.5982905982905983
confussion matrix:
[[751 282]
 [ 94 280]]
Best Parameter: {'var_smoothing': 1e-12}
Best Score: 0.7890723356074563

Not good performance so we are trying logistic regession

In [236]:
logi = LogisticRegression(max_iter=500)
log_param_grid = {
    'C': [0.01, 0.05, 0.1, 0.5, 1],
    'penalty': ['l1', 'l2'],
    'solver': ['liblinear'],
    'class_weight': [None, 'balanced']
}
logistic_grid = GridSearchCV(
    estimator=logi,
    param_grid=log_param_grid,
    cv= 5, 
    scoring='f1',
    n_jobs=-1
)
logistic_model = logistic_grid.fit(scale_xtrain_res, scale_ytrain_res)
print(f"Train Score: {logistic_model.score(scale_xtrain_res, scale_ytrain_res)}")
print(f"Test Score: {logistic_model.score(scale_xtest, ytest)}")
logistic_pred = logistic_model.predict(scale_xtest)
print(f"confusion_matrix:\n{confusion_matrix(ytest, logistic_pred)}")
print(f"accuracy_score: {accuracy_score(ytest, logistic_pred)}")
print(f"recall_score: {recall_score(ytest, logistic_pred)}")
print(f"f1_score: {f1_score(ytest, logistic_pred)}")
print(f"Best Parameter: {logistic_model.best_params_}")
print(f'Best Score: {logistic_model.best_score_}')

Train Score: 0.813073124853045
Test Score: 0.6061946902654868
confusion_matrix:
[[777 256]
 [100 274]]
accuracy_score: 0.7469793887704336
recall_score: 0.732620320855615
f1_score: 0.6061946902654868
Best Parameter: {'C': 0.5, 'class_weight': None, 'penalty': 'l1', 'solver': 'liblinear'}
Best Score: 0.8004808694295388

In [238]:
results = pd.DataFrame({
    'Model': ['Logistic Regression', 'KNN', 'Random Forest', 'XGBoost', 'GaussianNB', 'GaussianNB_after_tuning', 'Logistic_regression_after_tuning'],
    'Train Score': [0.8035, 0.8671, 0.9984, 0.9548, 0.7718, 0.7774, 0.8122],
    'Test Score': [0.7441, 0.7001, 0.7612, 0.7534, 0.7370, 0.6089, 0.6062],
    'Accuracy': [0.7441, 0.7001, 0.7697, 0.7534, 0.7370, 0.7370, 0.7469],
    'Recall': [0.7193, 0.7139, 0.6310, 0.6417, 0.7701, 0.7701, 0.7326],
    'F1 Score': [0.5991, 0.5586, 0.5930, 0.5804, 0.6089, 0.6089, 0.6062]
})
print("Evaluation Matrix with Scaling:")
results.sort_values(by='F1 Score', ascending=False)

Evaluation Matrix with Scaling:

,Model,Train Score,Test Score,Accuracy,Recall,F1 Score
4,GaussianNB,0.7718,0.7370,0.7370,0.7701,0.6089
5,GaussianNB_after_tuning,0.7774,0.6089,0.7370,0.7701,0.6089
6,Logistic_regression_after_tuning,0.8122,0.6062,0.7469,0.7326,0.6062
0,Logistic Regression,0.8035,0.7441,0.7441,0.7193,0.5991
2,Random Forest,0.9984,0.7612,0.7697,0.6310,0.5930
3,XGBoost,0.9548,0.7534,0.7534,0.6417,0.5804
1,KNN,0.8671,0.7001,0.7001,0.7139,0.5586